# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rate my course' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rate my course
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod "ElasticTransition"
  pod "MotionAnimation" 
  pod 'lottie-ios'
  pod 'MBProgressHUD'
  pod 'GrowingTextView'

  target 'rate my courseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rate my courseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
